[package]
name = "bevy-voxel-server"
version = "0.0.1"
edition = "2021"
authors = ["James Youngblood (soundeffects)"]
description = "Handles running the logic of a voxel game, for clients to connect to."
license = "MIT OR Apache"

[dependencies]
bevy = "0.7"
ndshape = "0.3.0"

[dev-dependencies]
bevy_flycam = "0.7"
